version: '3.5'
services:
  api:
    image: nickadam/ordig:1.1
    working_dir: /home/node/app
    command: bash -c 'while true; do npm start; done'
    environment:
      WG_NAME: {{WG_NAME}}
      WG_IP: {{WG_IP}}
      WG_POOL: {{WG_POOL}}
      WG_NAMESPACES: "{{WG_NAMESPACES | tojson}}" # Изменено: передача массива namespaces
      WG_NAMESERVER: {{WG_NAMESERVER}}
      WG_PORT: {{WG_PORT}}
      WG_ENDPOINT: {{WG_ENDPOINT}}
      WG_ALLOWED: {{WG_ALLOWED}}
      WG_SERVER_API_KEY: {{WG_SERVER_API_KEY}}
      WG_CLIENT_API_KEY: {{WG_CLIENT_API_KEY}}
    volumes:
      - type: bind
        source: /opt/ordig/data
        target: /data
  proxy:
    image: caddy/caddy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: ./public
        target: /var/www/html/public
      - type: bind
        source: /opt/ordig/caddy-data
        target: /data